project_name: Lockr
output_folder: docs
planning_artifacts: docs/planning
user_name: tusha
communication_language: English
document_output_language: English
user_skill_level: intermediate
date: 2026-04-15
